# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 9, 18, 55, 50, 961146, tzinfo=utc), verbose_name='date published'),
        ),
    ]
