# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0004_auto_20160509_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 22, 48, 24, 774047, tzinfo=utc), verbose_name='date published'),
        ),
    ]
