# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0007_auto_20160516_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
