# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0008_auto_20160516_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
