# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_list',
            field=models.CommaSeparatedIntegerField(max_length=200, null=True),
        ),
    ]
