# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0011_post_liked_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_list',
            field=models.CommaSeparatedIntegerField(default='', max_length=200),
        ),
    ]
