# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 22:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProjectRefactor', '0002_auto_20160506_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 22, 22, 12, 698807, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
